name: Update Google Sheet Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour

jobs:
  update_sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Decode GCP Credentials
      env:
        GCP_CREDENTIALS_BASE64: $
      run: |
        echo $GCP_CREDENTIALS_BASE64 | base64 --decode > credentials.json

    - name: Run script
      run: python update.py  # Update the path to your Python script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json